-- Schema capturado 1:1 desde Supabase (pg_dump --schema-only) el 2026-08-17.
-- Se recrea en Neon tal cual, con dos diferencias intencionales:
--   1. No se portan las policies de Row Level Security: dependían de
--      auth.uid()/roles anon-authenticated de Supabase Auth, que no existen
--      en Neon. El control de acceso pasa a la capa de API (Next.js / FastAPI).
--   2. No se agregan columnas nuevas todavía. La tabla `pedidos` real NO tiene
--      las columnas que las Edge Functions de pago (crear-pago/webhook-mp)
--      intentan escribir (preferencia_mp_id, pago_mp_id, pago_mp_status,
--      pago_mp_date, payment_details) -- el flujo de MercadoPago parece estar
--      roto hoy. Esas columnas se agregan recién en la Fase 7, cuando se
--      reimplementa el webhook de pago correctamente.

CREATE EXTENSION IF NOT EXISTS pgcrypto; -- para gen_random_uuid()

CREATE TABLE productos (
    "Id" bigint PRIMARY KEY,
    nombre text,
    precio bigint,
    categoria text,
    "Oferta" text,
    "Categoria" text,
    "Stock" boolean DEFAULT true,
    "Imagen" text,
    quantity integer DEFAULT 1,
    oferta_express boolean DEFAULT false,
    mas_vendido boolean DEFAULT false,
    solo_bulto boolean DEFAULT false NOT NULL
);

CREATE INDEX all_products ON productos USING btree (nombre, precio, "Imagen", "Stock");

CREATE TABLE categorias (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    categoria text NOT NULL
);

CREATE TABLE configuracion (
    id integer DEFAULT 1 PRIMARY KEY,
    precio_envio integer DEFAULT 7200 NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now(),
    banco text DEFAULT ''::text,
    titular text DEFAULT ''::text,
    alias text DEFAULT ''::text,
    cbu text DEFAULT ''::text
);

CREATE TABLE perfiles (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    nombre text NOT NULL,
    telefono text,
    tipo_cliente text,
    direccion text,
    rol text DEFAULT 'cliente'::text,
    email text,
    password text
);

CREATE TABLE pedidos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cliente text NOT NULL,
    telefono text,
    metodo text,
    direccion text,
    horario text,
    notas text,
    total numeric,
    carrito jsonb,
    user_id uuid DEFAULT gen_random_uuid(),
    estado text DEFAULT 'pendiente'::text,
    created_at timestamp with time zone DEFAULT now(),
    expira_en timestamp with time zone,
    fuente text DEFAULT 'manual'::text,
    descuento_aplicado smallint,
    fecha_modificacion timestamp without time zone,
    modificado_por text,
    metodo_pago text,
    fecha_pago timestamp with time zone,
    pagado_manualmente boolean
);

CREATE INDEX idx_pedidos_expira_en ON pedidos USING btree (expira_en);
CREATE INDEX idx_pedidos_fuente ON pedidos USING btree (fuente);

-- expires_at/attempts agregadas en la Fase 7: el código de reset de
-- contraseña siempre las esperó pero no existían en la tabla real
-- (el chequeo de expiración/intentos era un no-op silencioso en Supabase).
CREATE TABLE email_recovery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id text NOT NULL,
    token text,
    expires_at timestamptz,
    attempts integer NOT NULL DEFAULT 0
);

CREATE INDEX idx_email_recovery_profile_id ON email_recovery USING btree (profile_id);
CREATE INDEX idx_email_recovery_token ON email_recovery USING btree (token);

-- RPC de Supabase (supabase.rpc("obtener_ofertas_aleatorias")), portada tal cual.
CREATE OR REPLACE FUNCTION obtener_ofertas_aleatorias()
RETURNS SETOF productos
LANGUAGE sql
AS $$
  select *
  from productos
  where "Oferta" is not null
  order by random()
  limit 4;
$$;
