-- Migración: analítica de clientes en el admin.
-- Correr una vez contra la base de Neon (idempotente):
--   psql "$DATABASE_URL" -f web/db/migrations/0001_clientes_analytics.sql
-- o pegar en el SQL editor de Neon.

-- 1. Fecha de alta de cada cuenta (para "se registró y nunca compró").
ALTER TABLE perfiles
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

-- 2. Espejo del carrito del navegador para medir carritos abandonados
--    y tasa de conversión. Se escribe con upsert por session_id.
CREATE TABLE IF NOT EXISTS carrito_actividad (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL UNIQUE,
    user_id uuid,
    nombre text,
    telefono text,
    email text,
    items jsonb DEFAULT '[]'::jsonb,
    item_count integer NOT NULL DEFAULT 0,
    total numeric DEFAULT 0,
    convertido boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_carrito_actividad_updated_at ON carrito_actividad USING btree (updated_at);
CREATE INDEX IF NOT EXISTS idx_carrito_actividad_user_id ON carrito_actividad USING btree (user_id);
